# Generated by Django 3.2 on 2021-05-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('begin', models.DateField()),
                ('end', models.DateField()),
                ('number', models.IntegerField()),
            ],
        ),
    ]
